name: Build

on: [push, pull_request]

jobs:
  buildwin:
    runs-on: windows-latest
    steps:
    - name: Checkout git repo
      uses: actions/checkout@v2

    - name: Install Node and NPM
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: npm

    - name: Install and build
      run: |
        npm install
        npm run postinstall
        npm run build

    - name: Upload File
      uses: actions/upload-artifact@v2
      with:
        name: windows
        path: release/build/*exe

  buildmac:
    runs-on: macos-latest
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v2

      - name: Install Node and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install and build
        run: |
          npm install
          npm run postinstall
          npm run build

      - name: Upload File
        uses: actions/upload-artifact@v2
        with:
          name: mac
          path: release/build/*dmg
